In [16]:
import pandas as pd

df_new = pd.read_parquet("Datos/SL_HIDRO_DINAGUA_1980_2026.parquet")
df_old = pd.read_parquet("../fsda-lu-wq/data/imputations/imputations_SL_2025/datasets/SL_HIDRO_DINAGUA_1980_2025.parquet")

In [22]:
high

np.float64(nan)

In [23]:
df1_aligned

             Caudal (Q) [m3/s]                          \
           Fray Marcos DINAGUA Florida (Puente Ruta 5)
1980-02-01               9.326                     NaN
1980-02-02               9.326                     NaN
1980-02-03               9.326                     NaN
1980-02-04               9.326                     NaN
1980-02-05               9.326                     NaN
...                        ...                     ...
2025-05-29              30.876                     NaN
2025-05-30              17.876                     NaN
2025-05-31               8.408                     NaN
2025-06-01               5.850                     NaN
2025-06-02               4.705                     NaN

                                                                   \
           Paso Pache (Ruta 5 nueva) Picada de Varela Paso Roldan
1980-02-01                       NaN              NaN       0.192
1980-02-02                       NaN              NaN       0.192
1980-02-03                       NaN              NaN       0.192
1980-02-04                       NaN              NaN       0.168
1980-02-05                       NaN              NaN       0.176
...                              ...              ...         ...
2025-05-29                       NaN              NaN         NaN
2025-05-30                       NaN              NaN         NaN
2025-05-31                       NaN              NaN         NaN
2025-06-01                       NaN              NaN         NaN
2025-06-02                       NaN              NaN         NaN

                                                     Nivel de agua (h) [m]  \
           Paso de los Troncos Santa Lucia (Ruta 11)           Fray Marcos
1980-02-01               0.502                 0.941                   NaN
1980-02-02               0.502                 0.941                   NaN
1980-02-03               0.317                 0.941                   NaN
1980-02-04               0.317                 0.941                   NaN
1980-02-05               0.317                 0.941                   NaN
...                        ...                   ...                   ...
2025-05-29                 NaN                22.766                  1.43
2025-05-30                 NaN                63.905                  1.12
2025-05-31                 NaN                76.053                  0.78
2025-06-01               1.205                59.822                  0.64
2025-06-02               0.965                37.830                  0.55

                                                              \
           Florida (Puente Ruta 5) Paso Pache (Ruta 5 nueva)
1980-02-01                     NaN                       NaN
1980-02-02                     NaN                       NaN
1980-02-03                     NaN                       NaN
1980-02-04                     NaN                       NaN
1980-02-05                     NaN                       NaN
...                            ...                       ...
2025-05-29                     NaN                       NaN
2025-05-30                     NaN                       NaN
2025-05-31                     NaN                       NaN
2025-06-01                     NaN                       NaN
2025-06-02                     NaN                       NaN

                                                              \
           Presa Canelon Grande Picada de Varela Paso Roldan
1980-02-01                  NaN              NaN        2.90
1980-02-02                  NaN              NaN        2.90
1980-02-03                  NaN              NaN        2.90
1980-02-04                  NaN              NaN        2.89
1980-02-05                  NaN              NaN        2.89
...                         ...              ...         ...
2025-05-29                  NaN              NaN         NaN
2025-05-30                  NaN              NaN         NaN
2025-05-31                  NaN              NaN         NaN
2025-06-01                  NaN              NaN         NaN
2025-06-02                  NaN              NaN         NaN


           Paso de los Troncos Santa Lucia (Ruta 11) Las Brujas DINAGUA
1980-02-01                0.20                  1.00               1.57
1980-02-02                0.20                  1.00               0.70
1980-02-03                0.15                  1.00               0.82
1980-02-04                0.15                  1.00               1.23
1980-02-05                0.15                  1.00               1.23
...                        ...                   ...                ...
2025-05-29                 NaN                  1.67                NaN
2025-05-30                 NaN                  2.26                NaN
2025-05-31                 NaN                  2.46                NaN
2025-06-01                0.32                  2.19                NaN
2025-06-02                0.27                  1.86                NaN

[16559 rows x 16 columns]

In [29]:
import matplotlib.pyplot as plt
import re
import numpy as np

# Align both DataFrames (important!)
df1_aligned, df2_aligned = df_new.align(df_old, join="inner", axis=0)  # align index
df1_aligned, df2_aligned = df1_aligned.align(df2_aligned, join="inner", axis=1)  # align columns

# Loop through columns and plot
for col in df1_aligned.columns:

    var_name = re.sub(r"\([^)]*\)|\[[^\]]*\]|\{[^}]*\}", "", col[0])
    var_name = re.sub(r"\s+", " ", var_name).strip()

    unit = re.search(r"\[([^\]]*)\]", col[0])

    if unit:
        unit = unit.group(1)
    else:
        raise ValueError(f"No se encontro unidad para generar el plot ({col[0]})!")

    plt.figure(figsize=(10, 6))
    
    plt.xlabel(f"Log {var_name} nuevo [{unit}]")
    plt.ylabel(f"Log {var_name} viejo [{unit}]")
    plt.title(f"Diagrama de disperisón de '{var_name}' - Estación '{col[1]}'")
    
    # Optional: 1:1 reference line
    min_val = min(df1_aligned[col].min(), df2_aligned[col].min())
    max_val = max(df1_aligned[col].max(), df2_aligned[col].max())
    plt.plot([min_val, max_val], [min_val, max_val], linestyle='--', color="black", zorder=0)

    plt.scatter(df1_aligned[col], df2_aligned[col], s=10)

    plt.xscale("log")
    plt.yscale("log")


    # x = df1_aligned[col].dropna()
    # y = df2_aligned[col].dropna()

    # # Compute limits ignoring extreme values
    # low = min(np.percentile(x, 5), np.percentile(y, 5))
    # high = max(np.percentile(x, 95), np.percentile(y, 95))

    # plt.xlim(low, high)
    # plt.ylim(low, high)
    
    plt.savefig(f'scatter_plots/logs_plot_{var_name}_{col[1].replace(" ","_")}.png')
    plt.close()

In [39]:
df2

             Caudal (Q) [m3/s]                          \
station    Fray Marcos DINAGUA Florida (Puente Ruta 5)
date
1980-01-01               7.978                     0.0
1980-01-02               7.978                     0.0
1980-01-03               7.978                     0.0
1980-01-04               7.978                     0.0
1980-01-05               7.978                     0.0
...                        ...                     ...
2023-06-30               1.117                     NaN
2023-07-01               1.101                     NaN
2023-07-02               1.138                     NaN
2023-07-03               1.170                     NaN
2023-07-04               1.180                     NaN

                                                                   \
station    Paso Pache (Ruta 5 nueva) Picada de Varela Paso Roldan
date
1980-01-01                       NaN              NaN       0.359
1980-01-02                       NaN              NaN       0.359
1980-01-03                       NaN              NaN       0.359
1980-01-04                       NaN              NaN       0.318
1980-01-05                       NaN              NaN       0.318
...                              ...              ...         ...
2023-06-30                       NaN            0.369       0.219
2023-07-01                       NaN            0.376       0.223
2023-07-02                       NaN            0.379       0.217
2023-07-03                       NaN            0.380       0.237
2023-07-04                       NaN            0.378       0.235

                                                     Nivel de agua (h) [m]  \
station    Paso de los Troncos Santa Lucia (Ruta 11)           Fray Marcos
date
1980-01-01               0.959                 1.738                   NaN
1980-01-02               0.959                 1.738                   NaN
1980-01-03               0.959                 1.738                   NaN
1980-01-04               0.959                 1.738                   NaN
1980-01-05               0.959                 1.738                   NaN
...                        ...                   ...                   ...
2023-06-30                 NaN                 0.336                  0.13
2023-07-01                 NaN                 0.327                  0.13
2023-07-02                 NaN                 0.353                  0.13
2023-07-03                 NaN                 0.373                  0.14
2023-07-04                 NaN                 0.373                  0.14

                                                              \
station    Florida (Puente Ruta 5) Paso Pache (Ruta 5 nueva)
date
1980-01-01                     1.7                       NaN
1980-01-02                     1.7                       NaN
1980-01-03                     1.7                       NaN
1980-01-04                     1.7                       NaN
1980-01-05                     1.7                       NaN
...                            ...                       ...
2023-06-30                     NaN                       NaN
2023-07-01                     NaN                       NaN
2023-07-02                     NaN                       NaN
2023-07-03                     NaN                       NaN
2023-07-04                     NaN                       NaN

                                                              \
station    Presa Canelon Grande Picada de Varela Paso Roldan
date
1980-01-01                  NaN              NaN        2.95
1980-01-02                  NaN              NaN        2.95
1980-01-03                  NaN              NaN        2.95
1980-01-04                  NaN              NaN        2.94
1980-01-05                  NaN              NaN        2.94
...                         ...              ...         ...
2023-06-30                  NaN             0.37        2.93
2023-07-01                  NaN             0.38        2.93
2023-07-02                  NaN             0.38        2.93
2023-07-03                  NaN             0.38        2.93
2023-07-04                  NaN             0.38        2.93


station    Paso de los Troncos Santa Lucia (Ruta 11) Las Brujas DINAGUA
date
1980-01-01                 0.3                  1.10               1.37
1980-01-02                 0.3                  1.10               0.68
1980-01-03                 0.3                  1.10               1.30
1980-01-04                 0.3                  1.10               1.62
1980-01-05                 0.3                  1.10               0.99
...                        ...                   ...                ...
2023-06-30                 NaN                  0.89                NaN
2023-07-01                 NaN                  0.89                NaN
2023-07-02                 NaN                  0.90                NaN
2023-07-03                 NaN                  0.90                NaN
2023-07-04                 NaN                  0.90                NaN

[15891 rows x 16 columns]

In [15]:
df2

             Caudal (Q) [m3/s]                          \
station    Fray Marcos DINAGUA Florida (Puente Ruta 5)
date
1980-01-01               7.978                     0.0
1980-01-02               7.978                     0.0
1980-01-03               7.978                     0.0
1980-01-04               7.978                     0.0
1980-01-05               7.978                     0.0
...                        ...                     ...
2023-06-30               1.117                     NaN
2023-07-01               1.101                     NaN
2023-07-02               1.138                     NaN
2023-07-03               1.170                     NaN
2023-07-04               1.180                     NaN

                                                                   \
station    Paso Pache (Ruta 5 nueva) Picada de Varela Paso Roldan
date
1980-01-01                       NaN              NaN       0.359
1980-01-02                       NaN              NaN       0.359
1980-01-03                       NaN              NaN       0.359
1980-01-04                       NaN              NaN       0.318
1980-01-05                       NaN              NaN       0.318
...                              ...              ...         ...
2023-06-30                       NaN            0.369       0.219
2023-07-01                       NaN            0.376       0.223
2023-07-02                       NaN            0.379       0.217
2023-07-03                       NaN            0.380       0.237
2023-07-04                       NaN            0.378       0.235

                                                     Nivel de agua (h) [m]  \
station    Paso de los Troncos Santa Lucia (Ruta 11)           Fray Marcos
date
1980-01-01               0.959                 1.738                   NaN
1980-01-02               0.959                 1.738                   NaN
1980-01-03               0.959                 1.738                   NaN
1980-01-04               0.959                 1.738                   NaN
1980-01-05               0.959                 1.738                   NaN
...                        ...                   ...                   ...
2023-06-30                 NaN                 0.336                  0.13
2023-07-01                 NaN                 0.327                  0.13
2023-07-02                 NaN                 0.353                  0.13
2023-07-03                 NaN                 0.373                  0.14
2023-07-04                 NaN                 0.373                  0.14

                                                              \
station    Florida (Puente Ruta 5) Paso Pache (Ruta 5 nueva)
date
1980-01-01                     1.7                       NaN
1980-01-02                     1.7                       NaN
1980-01-03                     1.7                       NaN
1980-01-04                     1.7                       NaN
1980-01-05                     1.7                       NaN
...                            ...                       ...
2023-06-30                     NaN                       NaN
2023-07-01                     NaN                       NaN
2023-07-02                     NaN                       NaN
2023-07-03                     NaN                       NaN
2023-07-04                     NaN                       NaN

                                                              \
station    Presa Canelon Grande Picada de Varela Paso Roldan
date
1980-01-01                  NaN              NaN        2.95
1980-01-02                  NaN              NaN        2.95
1980-01-03                  NaN              NaN        2.95
1980-01-04                  NaN              NaN        2.94
1980-01-05                  NaN              NaN        2.94
...                         ...              ...         ...
2023-06-30                  NaN             0.37        2.93
2023-07-01                  NaN             0.38        2.93
2023-07-02                  NaN             0.38        2.93
2023-07-03                  NaN             0.38        2.93
2023-07-04                  NaN             0.38        2.93


station    Paso de los Troncos Santa Lucia (Ruta 11) Las Brujas DINAGUA
date
1980-01-01                 0.3                  1.10               1.37
1980-01-02                 0.3                  1.10               0.68
1980-01-03                 0.3                  1.10               1.30
1980-01-04                 0.3                  1.10               1.62
1980-01-05                 0.3                  1.10               0.99
...                        ...                   ...                ...
2023-06-30                 NaN                  0.89                NaN
2023-07-01                 NaN                  0.89                NaN
2023-07-02                 NaN                  0.90                NaN
2023-07-03                 NaN                  0.90                NaN
2023-07-04                 NaN                  0.90                NaN

[15891 rows x 16 columns]